FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/imgk/caddy-trojan

FROM caddy:latest AS caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy