name: 构建 LightPicture 镜像

on:
  push:
    branches: [main]
    paths: [light-picture/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: 检出源仓库
        uses: actions/checkout@v4
        with:
          repository: osuuu/LightPicture
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 缓存 Docker 构建层
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: 登录腾讯云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

      - name: 登录阿里云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: 登录 Docker 官方容器镜像服务
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 下载文件
        run: |
          wget -O "php.ini" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/light-picture/php.ini"
          wget -O "nginx.conf" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/light-picture/nginx.conf"
          wget -O "Dockerfile.prod" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/light-picture/Dockerfile.prod"
          wget -O "Dockerfile.install" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/light-picture/Dockerfile.install"

          mkdir app -p && wget -O "app/common.php" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/light-picture/common.php"

      - name: 文件目录结构
        run: tree -a -L 2

      - name: 构建镜像（部署版）
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.install
          push: true
          tags: |
            ccr.ccs.tencentyun.com/misaka-public/light-picture:install
            registry.cn-guangzhou.aliyuncs.com/misaka-public/light-picture:install
            docker.io/yangrucheng/light-picture:install
          labels: |
            image.source=LightPicture图床
            image.author=github.com/YangRucheng
          platforms: linux/amd64

      - name: 构建镜像（部署版）
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: |
            ccr.ccs.tencentyun.com/misaka-public/light-picture:latest
            registry.cn-guangzhou.aliyuncs.com/misaka-public/light-picture:latest
            docker.io/yangrucheng/light-picture:latest
          labels: |
            image.source=LightPicture图床
            image.author=github.com/YangRucheng
          platforms: linux/amd64
