name: 构建 订阅转换前端 镜像

on:
  push:
    branches: [main]
    paths: [sub-web/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: DyAxy/yet-another-sub-web

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 安装 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录腾讯云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

      - name: 登录阿里云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: 登录 GitHub 容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: yangrucheng
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 登录 Docker 官方容器镜像服务
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 下载文件
        run: |
          wget -O "config.ts" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/sub-web/config.ts"
          wget -O "Dockerfile" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/sub-web/Dockerfile"
          wget -O "replace.sh" "https://github.com/YangRucheng/Docker-Image/raw/refs/heads/main/sub-web/replace.sh"
          chmod +x replace.sh && bash replace.sh

      - name: 文件目录结构
        run: tree -a -L 2

      - name: 构建镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/yangrucheng/sub-web:latest
            docker.io/yangrucheng/sub-web:latest
            ccr.ccs.tencentyun.com/misaka-public/sub-web:latest
            registry.cn-guangzhou.aliyuncs.com/misaka-public/sub-web:latest
          labels: |
            image.source=订阅转换前端
            image.author=github.com/YangRucheng
          platforms: linux/amd64,linux/arm64
